I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/library.rpy", line 292, in script
    $ renpy.hide(custom_show("anna"))
  File "game/library.rpy", line 292, in <module>
    $ renpy.hide(custom_show("anna"))
TypeError: custom_show() missing 1 required positional argument: 'emotion'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/library.rpy", line 292, in script
    $ renpy.hide(custom_show("anna"))
  File "C:\Users\Kim\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Kim\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/library.rpy", line 292, in <module>
    $ renpy.hide(custom_show("anna"))
TypeError: custom_show() missing 1 required positional argument: 'emotion'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Call It Fate 1.0
Fri Aug 30 16:56:04 2024
